version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "Installing Terraform..."
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo "Starting Terraform deployment..."
      - cd terraform
      - terraform init -input=false
      - terraform apply -auto-approve -input=false