version: 0.2

phases:
  install:
    commands:
      - echo "Installing required packages..."
      - apt-get update -y
      - apt-get install -y unzip

      - echo "Downloading Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip

      - unzip terraform.zip
      - mv terraform /usr/local/bin/terraform
      - chmod +x /usr/local/bin/terraform

      - terraform version

  build:
    commands:
      - cd terraform
      - terraform init
      - terraform apply -auto-approve