version: 0.2

phases:
  install:
    commands:
      - curl -s -ql -o terraform_install.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - echo "Starting Terraform deployment..."
      - cd ./terraform
      - terraform init
      - terraform apply -auto-approve
